on: [push]
  
jobs:
  nuon_model_visualizer_job:
    runs-on: ubuntu-latest
    name: NuonModelVisualizer
    steps:
    - uses: actions/checkout@v2
      name: Check out code
    - name: Login to DockerHub
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker Python SDK image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/nuon-model-visualizer:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
